### ISSUE TITLE
Package of example does not work

### ISSUE THREAD

**Issue by Blackdread** [roskenet/spring-javafx-examples#10]
Just clone examples, launch package of maven then try to run the part_1 jar, it fails.
I think you configured wrong way the [springboot-javafx-support](https://github.com/roskenet/springboot-javafx-support) or the examples.
Due to this error, it is not possible to create a simple app that can be put in a jar and sent to someone else.
The app can be launched from the IDE (Intellij IDEA).

> 14:07:24.445 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.core.env.StandardEnvironment - Adding PropertySource 'systemProperties' with lowest search precedence
> 14:07:24.448 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.core.env.StandardEnvironment - Adding PropertySource 'systemEnvironment' with lowest search precedence
> 14:07:24.449 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.core.env.StandardEnvironment - Initialized StandardEnvironment with PropertySources [MapPropertySource@613512957 {name='systemProperties', properties={sun.desktop=windows, awt.toolkit=sun.awt.windows.WToolkit, java.specification.version=10, file.encoding.pkg=sun.io, javafx.runtime.version=10.0.2+13, sun.cpu.isalist=amd64, sun.jnu.encoding=Cp1252, java.class.path=part-1-0.0.1.jar, sun.awt.enableExtraMouseButtons=true, java.vm.vendor="Oracle Corporation", sun.arch.data.model=64, user.variant=, java.vendor.url=http://java.oracle.com/, user.timezone=Asia/Shanghai, os.name=Windows 10, java.vm.specification.version=10, javafx.version=10.0.2, sun.java.launcher=SUN_STANDARD, user.country=US, sun.boot.library.path=C:\Program Files\Java\jre-10.0.2\bin, sun.java.command=part-1-0.0.1.jar, jdk.debug=release, sun.cpu.endian=little, user.home=C:\Users\yoann, user.language=en, sun.stderr.encoding=cp437, java.specification.vendor=Oracle Corporation, java.version.date=2018-07-17, java.home=C:\Program Files\Java\jre-10.0.2, file.separator=\, java.vm.compressedOopsMode=Zero based, line.separator=
> , java.specification.name=Java Platform API Specification, java.vm.specification.vendor=Oracle Corporation, java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment, java.awt.headless=true, user.script=, java.protocol.handler.pkgs=org.springframework.boot.loader, sun.management.compiler=HotSpot 64-Bit Tiered Compilers, java.runtime.version=10.0.2+13, user.name=yoann, path.separator=;, os.version=10.0, java.runtime.name=Java(TM) SE Runtime Environment, file.encoding=Cp1252, java.vm.name=Java HotSpot(TM) 64-Bit Server VM, java.vendor.version=18.3, java.vendor.url.bug=http://bugreport.java.com/bugreport/, java.io.tmpdir=C:\Users\yoann\AppData\Local\Temp\, java.version=10.0.2, user.dir=C:\Users\yoann\Documents\code\development_open_source\spring-javafx-examples\part_1\target, os.arch=amd64, java.vm.specification.name=Java Virtual Machine Specification, java.awt.printerjob=sun.awt.windows.WPrinterJob, sun.os.patch.level=, java.library.path=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\MySQL\MySQL Utilities 1.6\;C:\Program Files\Git LFS;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\maven\bin;C:\Program Files\PuTTY\;C:\Python27;C:\Python27\Scripts;C:\wamp64\bin\mysql\mysql5.7.21\bin;C:\Program Files (x86)\Yarn\bin\;C:\Users\yoann\AppData\Local\Microsoft\WindowsApps;C:\Users\yoann\AppData\Roaming\npm;C:\Users\yoann\AppData\Local\Yarn\bin;C:\wamp64\bin\php\php5.6.35;;., java.vendor=Oracle Corporation, java.vm.info=mixed mode, java.vm.version=10.0.2+13, sun.io.unicode.encoding=UnicodeLittle, java.class.version=54.0}}, SystemEnvironmentPropertySource@1420721028 {name='systemEnvironment', properties={USERDOMAIN_ROAMINGPROFILE=ALLURESYS, LOCALAPPDATA=C:\Users\yoann\AppData\Local, PROCESSOR_LEVEL=6, USERDOMAIN=ALLURESYS, FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer, LOGONSERVER=\\DC-01, JAVA_HOME=C:\Program Files\Java\jdk1.8.0_172, PROMPT=$P$G, SESSIONNAME=Console, ALLUSERSPROFILE=C:\ProgramData, PROCESSOR_ARCHITECTURE=AMD64, PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Intel\Wired Networking\, SystemDrive=C:, =ExitCode=00000000, OneDrive=C:\Users\yoann\OneDrive, =C:=C:\Users\yoann\Documents\code\development_open_source\spring-javafx-examples\part_1\target, APPDATA=C:\Users\yoann\AppData\Roaming, USERNAME=yoann, USERDNSDOMAIN=ALLURESYS.COM, ProgramFiles(x86)=C:\Program Files (x86), CommonProgramFiles=C:\Program Files\Common Files, Path=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\MySQL\MySQL Utilities 1.6\;C:\Program Files\Git LFS;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\maven\bin;C:\Program Files\PuTTY\;C:\Python27;C:\Python27\Scripts;C:\wamp64\bin\mysql\mysql5.7.21\bin;C:\Program Files (x86)\Yarn\bin\;C:\Users\yoann\AppData\Local\Microsoft\WindowsApps;C:\Users\yoann\AppData\Roaming\npm;C:\Users\yoann\AppData\Local\Yarn\bin;C:\wamp64\bin\php\php5.6.35;, FPS_BROWSER_USER_PROFILE_STRING=Default, PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC, DriverData=C:\Windows\System32\Drivers\DriverData, OS=Windows_NT, COMPUTERNAME=PC-YOANN, PROCESSOR_REVISION=9e0a, CommonProgramW6432=C:\Program Files\Common Files, ComSpec=C:\WINDOWS\system32\cmd.exe, ProgramData=C:\ProgramData, GIT_LFS_PATH=C:\Program Files\Git LFS, ProgramW6432=C:\Program Files, HOMEPATH=\Users\yoann, SystemRoot=C:\WINDOWS, TEMP=C:\Users\yoann\AppData\Local\Temp, HOMEDRIVE=C:, PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 10, GenuineIntel, USERPROFILE=C:\Users\yoann, TMP=C:\Users\yoann\AppData\Local\Temp, CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files, ProgramFiles=C:\Program Files, PUBLIC=C:\Users\Public, NUMBER_OF_PROCESSORS=12, windir=C:\WINDOWS, =::=::\}}]
> 14:07:24.450 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'spring.profiles.active' in any property source
> 14:07:24.450 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'spring.profiles.active' in any property source
> 14:07:24.542 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.core.env.StandardEnvironment - Adding PropertySource 'configurationProperties' with highest search precedence
> 14:07:24.543 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'spring.beaninfo.ignore' in any property source
> 14:07:24.544 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'spring.banner.image.location' in any property source
> 14:07:24.548 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'spring.banner.location' in any property source
> 
>   .   ____          _            __ _ _
>  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
> ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
>  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
>   '  |____| .__|_| |_|_| |_\__, | / / / /
>  =========|_|==============|___/=/_/_/_/
>  :: Spring Boot ::        (v2.0.0.RELEASE)
> 
> 14:07:24.574 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.core.env.StandardEnvironment - Adding PropertySource 'systemProperties' with lowest search precedence
> 14:07:24.574 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.core.env.StandardEnvironment - Adding PropertySource 'systemEnvironment' with lowest search precedence
> 14:07:24.574 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.core.env.StandardEnvironment - Initialized StandardEnvironment with PropertySources [MapPropertySource@239407842 {name='systemProperties', properties={sun.desktop=windows, awt.toolkit=sun.awt.windows.WToolkit, java.specification.version=10, file.encoding.pkg=sun.io, javafx.runtime.version=10.0.2+13, sun.cpu.isalist=amd64, sun.jnu.encoding=Cp1252, java.class.path=part-1-0.0.1.jar, sun.awt.enableExtraMouseButtons=true, java.vm.vendor="Oracle Corporation", sun.arch.data.model=64, user.variant=, java.vendor.url=http://java.oracle.com/, user.timezone=Asia/Shanghai, os.name=Windows 10, java.vm.specification.version=10, javafx.version=10.0.2, sun.java.launcher=SUN_STANDARD, user.country=US, sun.boot.library.path=C:\Program Files\Java\jre-10.0.2\bin, sun.java.command=part-1-0.0.1.jar, jdk.debug=release, sun.cpu.endian=little, user.home=C:\Users\yoann, user.language=en, sun.stderr.encoding=cp437, java.specification.vendor=Oracle Corporation, java.version.date=2018-07-17, java.home=C:\Program Files\Java\jre-10.0.2, file.separator=\, java.vm.compressedOopsMode=Zero based, line.separator=
> , java.specification.name=Java Platform API Specification, java.vm.specification.vendor=Oracle Corporation, java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment, java.awt.headless=true, user.script=, java.protocol.handler.pkgs=org.springframework.boot.loader, sun.management.compiler=HotSpot 64-Bit Tiered Compilers, java.runtime.version=10.0.2+13, user.name=yoann, path.separator=;, os.version=10.0, java.runtime.name=Java(TM) SE Runtime Environment, file.encoding=Cp1252, spring.beaninfo.ignore=true, java.vm.name=Java HotSpot(TM) 64-Bit Server VM, java.vendor.version=18.3, java.vendor.url.bug=http://bugreport.java.com/bugreport/, java.io.tmpdir=C:\Users\yoann\AppData\Local\Temp\, java.version=10.0.2, user.dir=C:\Users\yoann\Documents\code\development_open_source\spring-javafx-examples\part_1\target, os.arch=amd64, java.vm.specification.name=Java Virtual Machine Specification, java.awt.printerjob=sun.awt.windows.WPrinterJob, sun.os.patch.level=, java.library.path=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\MySQL\MySQL Utilities 1.6\;C:\Program Files\Git LFS;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\maven\bin;C:\Program Files\PuTTY\;C:\Python27;C:\Python27\Scripts;C:\wamp64\bin\mysql\mysql5.7.21\bin;C:\Program Files (x86)\Yarn\bin\;C:\Users\yoann\AppData\Local\Microsoft\WindowsApps;C:\Users\yoann\AppData\Roaming\npm;C:\Users\yoann\AppData\Local\Yarn\bin;C:\wamp64\bin\php\php5.6.35;;., java.vendor=Oracle Corporation, java.vm.info=mixed mode, java.vm.version=10.0.2+13, sun.io.unicode.encoding=UnicodeLittle, java.class.version=54.0}}, SystemEnvironmentPropertySource@831220591 {name='systemEnvironment', properties={USERDOMAIN_ROAMINGPROFILE=ALLURESYS, LOCALAPPDATA=C:\Users\yoann\AppData\Local, PROCESSOR_LEVEL=6, USERDOMAIN=ALLURESYS, FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer, LOGONSERVER=\\DC-01, JAVA_HOME=C:\Program Files\Java\jdk1.8.0_172, PROMPT=$P$G, SESSIONNAME=Console, ALLUSERSPROFILE=C:\ProgramData, PROCESSOR_ARCHITECTURE=AMD64, PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Intel\Wired Networking\, SystemDrive=C:, =ExitCode=00000000, OneDrive=C:\Users\yoann\OneDrive, =C:=C:\Users\yoann\Documents\code\development_open_source\spring-javafx-examples\part_1\target, APPDATA=C:\Users\yoann\AppData\Roaming, USERNAME=yoann, USERDNSDOMAIN=ALLURESYS.COM, ProgramFiles(x86)=C:\Program Files (x86), CommonProgramFiles=C:\Program Files\Common Files, Path=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\MySQL\MySQL Utilities 1.6\;C:\Program Files\Git LFS;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\maven\bin;C:\Program Files\PuTTY\;C:\Python27;C:\Python27\Scripts;C:\wamp64\bin\mysql\mysql5.7.21\bin;C:\Program Files (x86)\Yarn\bin\;C:\Users\yoann\AppData\Local\Microsoft\WindowsApps;C:\Users\yoann\AppData\Roaming\npm;C:\Users\yoann\AppData\Local\Yarn\bin;C:\wamp64\bin\php\php5.6.35;, FPS_BROWSER_USER_PROFILE_STRING=Default, PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC, DriverData=C:\Windows\System32\Drivers\DriverData, OS=Windows_NT, COMPUTERNAME=PC-YOANN, PROCESSOR_REVISION=9e0a, CommonProgramW6432=C:\Program Files\Common Files, ComSpec=C:\WINDOWS\system32\cmd.exe, ProgramData=C:\ProgramData, GIT_LFS_PATH=C:\Program Files\Git LFS, ProgramW6432=C:\Program Files, HOMEPATH=\Users\yoann, SystemRoot=C:\WINDOWS, TEMP=C:\Users\yoann\AppData\Local\Temp, HOMEDRIVE=C:, PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 10, GenuineIntel, USERPROFILE=C:\Users\yoann, TMP=C:\Users\yoann\AppData\Local\Temp, CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files, ProgramFiles=C:\Program Files, PUBLIC=C:\Users\Public, NUMBER_OF_PROCESSORS=12, windir=C:\WINDOWS, =::=::\}}]
> 14:07:24.591 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.context.annotation.ClassPathBeanDefinitionScanner - JSR-250 'javax.annotation.ManagedBean' found and supported for component scanning
> 14:07:24.613 [ForkJoinPool.commonPool-worker-25] INFO org.springframework.boot.SpringApplication - Starting application on PC-YOANN with PID 13448 (C:\Users\yoann\Documents\code\development_open_source\spring-javafx-examples\part_1\target\part-1-0.0.1.jar started by yoann in C:\Users\yoann\Documents\code\development_open_source\spring-javafx-examples\part_1\target)
> 14:07:24.614 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.boot.SpringApplication - Running with Spring Boot v2.0.0.RELEASE, Spring v5.0.4.RELEASE
> 14:07:24.614 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'spring.profiles.active' in any property source
> 14:07:24.614 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'spring.profiles.default' in any property source
> 14:07:24.614 [ForkJoinPool.commonPool-worker-25] INFO org.springframework.boot.SpringApplication - No active profile set, falling back to default profiles: default
> 14:07:24.614 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.boot.SpringApplication - Loading source class example.Main
> 14:07:24.619 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.context.annotation.ClassPathBeanDefinitionScanner - JSR-250 'javax.annotation.ManagedBean' found and supported for component scanning
> 14:07:24.644 [ForkJoinPool.commonPool-worker-25] INFO org.springframework.context.annotation.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@59e617b2: startup date [Mon Aug 06 14:07:24 CST 2018]; root of context hierarchy
> 14:07:24.645 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.context.annotation.AnnotationConfigApplicationContext - Bean factory for org.springframework.context.annotation.AnnotationConfigApplicationContext@59e617b2: org.springframework.beans.factory.support.DefaultListableBeanFactory@3205d56a: defining beans [org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.event.internalEventListenerProcessor,org.springframework.context.event.internalEventListenerFactory,main]; root of factory hierarchy
> 14:07:24.651 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'org.springframework.context.annotation.internalConfigurationAnnotationProcessor'
> 14:07:24.651 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating instance of bean 'org.springframework.context.annotation.internalConfigurationAnnotationProcessor'
> 14:07:24.656 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Eagerly caching bean 'org.springframework.context.annotation.internalConfigurationAnnotationProcessor' to allow for resolving potential circular references
> 14:07:24.657 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Finished creating instance of bean 'org.springframework.context.annotation.internalConfigurationAnnotationProcessor'
> 14:07:24.670 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.context.annotation.ClassPathBeanDefinitionScanner - JSR-250 'javax.annotation.ManagedBean' found and supported for component scanning
> 14:07:24.671 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.core.io.support.PathMatchingResourcePatternResolver - Resolved classpath location [example/] to resources []
> 14:07:24.671 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.core.io.support.PathMatchingResourcePatternResolver - Resolved location pattern [classpath*:example/**/*.class] to resources []
> 14:07:24.674 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.core.env.PropertySourcesPropertyResolver - Could not find key 'spring.boot.enableautoconfiguration' in any property source
> 14:07:24.676 [ForkJoinPool.commonPool-worker-25] WARN org.springframework.context.annotation.AnnotationConfigApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [example.Main]; nested exception is java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
> 14:07:24.676 [ForkJoinPool.commonPool-worker-25] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@3205d56a: defining beans [org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.event.internalEventListenerProcessor,org.springframework.context.event.internalEventListenerFactory,main]; root of factory hierarchy
> 14:07:24.680 [ForkJoinPool.commonPool-worker-25] ERROR org.springframework.boot.SpringApplication - Application run failed
> org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [example.Main]; nested exception is java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
> 	at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:556)
> 	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:184)
> 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:316)
> 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:233)
> 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273)
> 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:93)
> 	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:693)
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
> 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
> 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234)
> 	at de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport.lambda$init$1(AbstractJavaFxApplicationSupport.java:124)
> 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
> 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
> Caused by: java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
> 	at org.springframework.util.Assert.notEmpty(Assert.java:450)
> 	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getCandidateConfigurations(AutoConfigurationImportSelector.java:158)
> 	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.selectImports(AutoConfigurationImportSelector.java:95)
> 	at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:547)
> 	... 18 common frames omitted
> 14:07:24.681 [ForkJoinPool.commonPool-worker-25] ERROR de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport - Failed to load spring application context: 
> java.util.concurrent.CompletionException: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [example.Main]; nested exception is java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
> 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
> 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
> 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
> 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
> Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [example.Main]; nested exception is java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
> 	at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:556)
> 	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:184)
> 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:316)
> 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:233)
> 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273)
> 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:93)
> 	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:693)
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
> 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752)
> 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234)
> 	at de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport.lambda$init$1(AbstractJavaFxApplicationSupport.java:124)
> 	... 5 common frames omitted
> Caused by: java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
> 	at org.springframework.util.Assert.notEmpty(Assert.java:450)
> 	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getCandidateConfigurations(AutoConfigurationImportSelector.java:158)
> 	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.selectImports(AutoConfigurationImportSelector.java:95)
> 	at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:547)
> 	... 18 common frames omitted
>

**Comment by Blackdread** [comment]
Sorry, I finally made it work.
I have java 8 and 10 installed.
JAVA_HOME is set to jdk 8 (so maven use jdk8)
javapath is 10

I have changed PATH, and put in front of "C:\Program Files (x86)\Common Files\Oracle\Java\javapath" -> "C:\Program Files\Java\jdk1.8.0_172\bin" so I can do "java -jar my.jar" and it will work.
If I double-click on the jar, I still get same error.

I think can close this issue, I tried to check your poms but seems all good to me.
