### ISSUE TITLE
javafx started and then crashed 

### ISSUE THREAD

**Issue by alrazihi** [roskenet/spring-javafx-examples#7]
16:32:52.014 [ForkJoinPool.commonPool-worker-1] ERROR de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport - Failed to load spring application context: 
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: org.springframework.boot.SpringApplication.run(Ljava/lang/Class;[Ljava/lang/String;)Lorg/springframework/context/ConfigurableApplicationContext;
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:283)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Caused by: java.lang.NoSuchMethodError: org.springframework.boot.SpringApplication.run(Ljava/lang/Class;[Ljava/lang/String;)Lorg/springframework/context/ConfigurableApplicationContext;
	at de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport.lambda$init$1(AbstractJavaFxApplicationSupport.java:122)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	... 4 common frames omitted

**Comment by krystofurr** [comment]
I was getting the same error in my projects.  I'm using Spring Roo 2.0.0.RC2 and it was working fine.  It seems that in October the project's Spring Boot Parent was updated to 2.0.0 M5.  If I use version 1.4.5 it works fine.  If I use the 2.0 versions, I get the same error.

**Comment by roskenet** [comment]
Please see:
https://github.com/roskenet/spring-javafx-examples/issues/6
