### ISSUE TITLE
JavaFX cannot start

### ISSUE THREAD

**Issue by XShandow** [roskenet/spring-javafx-examples#8]
E:\JDK\Java8u144_64\bin\java -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=21194 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2017.3.2\lib\idea_rt.jar=21195:C:\Program Files\JetBrains\IntelliJ IDEA 2017.3.2\bin" -Dfile.encoding=UTF-8 -classpath E:\JDK\Java8u144_64\jre\lib\charsets.jar;E:\JDK\Java8u144_64\jre\lib\deploy.jar;E:\JDK\Java8u144_64\jre\lib\ext\access-bridge-64.jar;E:\JDK\Java8u144_64\jre\lib\ext\cldrdata.jar;E:\JDK\Java8u144_64\jre\lib\ext\dnsns.jar;E:\JDK\Java8u144_64\jre\lib\ext\jaccess.jar;E:\JDK\Java8u144_64\jre\lib\ext\jfxrt.jar;E:\JDK\Java8u144_64\jre\lib\ext\localedata.jar;E:\JDK\Java8u144_64\jre\lib\ext\nashorn.jar;E:\JDK\Java8u144_64\jre\lib\ext\sunec.jar;E:\JDK\Java8u144_64\jre\lib\ext\sunjce_provider.jar;E:\JDK\Java8u144_64\jre\lib\ext\sunmscapi.jar;E:\JDK\Java8u144_64\jre\lib\ext\sunpkcs11.jar;E:\JDK\Java8u144_64\jre\lib\ext\zipfs.jar;E:\JDK\Java8u144_64\jre\lib\javaws.jar;E:\JDK\Java8u144_64\jre\lib\jce.jar;E:\JDK\Java8u144_64\jre\lib\jfr.jar;E:\JDK\Java8u144_64\jre\lib\jfxswt.jar;E:\JDK\Java8u144_64\jre\lib\jsse.jar;E:\JDK\Java8u144_64\jre\lib\management-agent.jar;E:\JDK\Java8u144_64\jre\lib\plugin.jar;E:\JDK\Java8u144_64\jre\lib\resources.jar;E:\JDK\Java8u144_64\jre\lib\rt.jar;E:\Code\Java\Intellij\KiTool\target\classes;C:\Users\xujianchao\.m2\repository\org\springframework\boot\spring-boot-starter\2.0.0.M6\spring-boot-starter-2.0.0.M6.jar;C:\Users\xujianchao\.m2\repository\org\springframework\boot\spring-boot\2.0.0.M6\spring-boot-2.0.0.M6.jar;C:\Users\xujianchao\.m2\repository\org\springframework\spring-context\5.0.1.RELEASE\spring-context-5.0.1.RELEASE.jar;C:\Users\xujianchao\.m2\repository\org\springframework\spring-aop\5.0.1.RELEASE\spring-aop-5.0.1.RELEASE.jar;C:\Users\xujianchao\.m2\repository\org\springframework\spring-beans\5.0.1.RELEASE\spring-beans-5.0.1.RELEASE.jar;C:\Users\xujianchao\.m2\repository\org\springframework\spring-expression\5.0.1.RELEASE\spring-expression-5.0.1.RELEASE.jar;C:\Users\xujianchao\.m2\repository\org\springframework\boot\spring-boot-autoconfigure\2.0.0.M6\spring-boot-autoconfigure-2.0.0.M6.jar;C:\Users\xujianchao\.m2\repository\org\springframework\boot\spring-boot-starter-logging\2.0.0.M6\spring-boot-starter-logging-2.0.0.M6.jar;C:\Users\xujianchao\.m2\repository\ch\qos\logback\logback-classic\1.2.3\logback-classic-1.2.3.jar;C:\Users\xujianchao\.m2\repository\ch\qos\logback\logback-core\1.2.3\logback-core-1.2.3.jar;C:\Users\xujianchao\.m2\repository\org\slf4j\slf4j-api\1.7.25\slf4j-api-1.7.25.jar;C:\Users\xujianchao\.m2\repository\org\apache\logging\log4j\log4j-to-slf4j\2.9.1\log4j-to-slf4j-2.9.1.jar;C:\Users\xujianchao\.m2\repository\org\apache\logging\log4j\log4j-api\2.9.1\log4j-api-2.9.1.jar;C:\Users\xujianchao\.m2\repository\org\slf4j\jul-to-slf4j\1.7.25\jul-to-slf4j-1.7.25.jar;C:\Users\xujianchao\.m2\repository\org\slf4j\log4j-over-slf4j\1.7.25\log4j-over-slf4j-1.7.25.jar;C:\Users\xujianchao\.m2\repository\javax\annotation\javax.annotation-api\1.3.1\javax.annotation-api-1.3.1.jar;C:\Users\xujianchao\.m2\repository\org\springframework\spring-core\5.0.1.RELEASE\spring-core-5.0.1.RELEASE.jar;C:\Users\xujianchao\.m2\repository\org\springframework\spring-jcl\5.0.1.RELEASE\spring-jcl-5.0.1.RELEASE.jar;C:\Users\xujianchao\.m2\repository\org\yaml\snakeyaml\1.19\snakeyaml-1.19.jar;C:\Users\xujianchao\.m2\repository\de\roskenet\springboot-javafx-support\2.1.5\springboot-javafx-support-2.1.5.jar main.Main

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::             (v2.0.0.M6)

2018-03-01 09:15:45.746  INFO 6356 --- [onPool-worker-1] o.s.boot.SpringApplication               : Starting application on xujc0503 with PID 6356 (started by xujianchao in E:\Code\Java\Intellij\KiTool)
2018-03-01 09:15:45.750  INFO 6356 --- [onPool-worker-1] o.s.boot.SpringApplication               : No active profile set, falling back to default profiles: default
2018-03-01 09:15:45.827  INFO 6356 --- [onPool-worker-1] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@56327b3: startup date [Thu Mar 01 09:15:45 CST 2018]; root of context hierarchy
2018-03-01 09:15:46.570  INFO 6356 --- [onPool-worker-1] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2018-03-01 09:15:46.595  INFO 6356 --- [onPool-worker-1] o.s.boot.SpringApplication               : Started application in 1.62 seconds (JVM running for 4.1)
2018-03-01 09:15:46.602 ERROR 6356 --- [lication Thread] d.f.j.AbstractJavaFxApplicationSupport   : Failed to load application: 

org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'index.HelloworldView' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:348) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:335) ~[spring-beans-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1101) ~[spring-context-5.0.1.RELEASE.jar:5.0.1.RELEASE]
	at de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport.showView(AbstractJavaFxApplicationSupport.java:212) [springboot-javafx-support-2.1.5.jar:na]
	at de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport.showInitialView(AbstractJavaFxApplicationSupport.java:193) [springboot-javafx-support-2.1.5.jar:na]
	at de.felixroske.jfxsupport.AbstractJavaFxApplicationSupport.lambda$start$5(AbstractJavaFxApplicationSupport.java:159) [springboot-javafx-support-2.1.5.jar:na]
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295) ~[jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_144]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294) ~[jfxrt.jar:na]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191) ~[jfxrt.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_144]

2018-03-01 09:15:48.391  INFO 6356 --- [lication Thread] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@56327b3: startup date [Thu Mar 01 09:15:45 CST 2018]; root of context hierarchy
2018-03-01 09:15:48.397  INFO 6356 --- [lication Thread] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown

Process finished with exit code 0

**Comment by XShandow** [comment]
my pom.xml

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.kitool</groupId>
    <artifactId>KiTool</artifactId>
    <version>1.0-SNAPSHOT</version>


    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.0.M6</version>
        <relativePath/> 
    </parent>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>1.8</java.version>
        <springboot-javafx.version>2.1.5</springboot-javafx.version>
    </properties>

    
    <repositories>
        <repository>
            <id>spring-snapshots</id>
            <url>http://repo.spring.io/snapshot</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>spring-milestones</id>
            <url>http://repo.spring.io/milestone</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>spring-snapshots</id>
            <url>http://repo.spring.io/snapshot</url>
        </pluginRepository>
        <pluginRepository>
            <id>spring-milestones</id>
            <url>http://repo.spring.io/milestone</url>
        </pluginRepository>
    </pluginRepositories>

    

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>de.roskenet</groupId>
            <artifactId>springboot-javafx-support</artifactId>
            <version>${springboot-javafx.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>

**Comment by XShandow** [comment]
I sove it.when use the method

> launch(Main.class, IndexView.class,args);
the Main.class and indexView.class must be in the same package.
